### ISSUE TITLE
Dissolution legacy crashes inside dev envroniment

### ISSUE THREAD

**Issue by Derailedzack** [Ladysnake/Dissolution-Legacy#23]
The minecraft test environment crashes because of the betweenlands
[08:46:53] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: ---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/14/21 8:46 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: thebetweenlands Failed to load new mod instance.
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.init(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:187)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:601)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: thebetweenlands/core/TheBetweenlandsPreconditions
	at thebetweenlands.common.TheBetweenlands.createInstance(TheBetweenlands.java:164)
	... 48 more
Caused by: java.lang.ClassNotFoundException: thebetweenlands.core.TheBetweenlandsPreconditions
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 49 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 51 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 394213960 bytes (375 MB) / 617086976 bytes (588 MB) up to 3814195200 bytes (3637 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version         | Source                                                            | Signature                                |
	|:----- |:----------------- |:--------------- |:----------------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft         | 1.12.2          | minecraft.jar                                                     | None                                     |
	| LC    | mcp               | 9.42            | minecraft.jar                                                     | None                                     |
	| LC    | FML               | 8.0.99.99       | forgeSrc-1.12.2-14.23.5.2846-PROJECT(Dissolution-Legacy-1.12).jar | None                                     |
	| LC    | forge             | 14.23.5.2846    | forgeSrc-1.12.2-14.23.5.2846-PROJECT(Dissolution-Legacy-1.12).jar | None                                     |
	| LC    | clothesline-hooks | 1.12.2-0.0.1.0  | minecraft.jar                                                     | None                                     |
	| LC    | albedocore        | 0.1             | minecraft.jar                                                     | None                                     |
	| LC    | ladylib           | 2.6.2           | Ladylib-2.6.2.jar                                                 | None                                     |
	| LC    | albedo            | 0.1.3           | albedo-0.1.3.jar                                                  | None                                     |
	| LC    | baubles           | 1.5.2           | Baubles-1.12-1.5.2.jar                                            | None                                     |
	| LC    | thaumcraft        | 6.1.BETA26      | Thaumcraft-1.12.2.jar                                             | None                                     |
	| LC    | dissolution       | 0.3.13          | main                                                              | None                                     |
	| LC    | ichunutil         | 7.1.4           | iChunUtil-1.12.2-7.1.4.jar                                        | None                                     |
	| LC    | sync              | 7.0.2           | Sync-1.12.2-7.0.2.jar                                             | None                                     |
	| LE    | thebetweenlands   | 3.7.3           | TheBetweenlands-3.7.3-universal.jar                               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| L     | modwinder         | 1.1             | Ladylib-2.6.2.jar                                                 | None                                     |
	| L     | mantle            | 1.12-1.3.1.22   | Mantle-1.12-1.3.1.22.jar                                          | None                                     |
	| L     | inspirations      | 1.12.2-0.2.3.58 | Inspirations-1.12.2-0.2.3.58.jar                                  | None                                     |
	| L     | potioncore        | 1.6_for_1.12.2  | PotionCore-1.6_for_1.12.2.jar                                     | None                                     |
	| L     | journeymap        | 1.12.2-5.5.3    | journeymap-1.12.2.jar                                             | None                                     |
	| L     | aether_legacy     | 1.4.4           | aether_legacy-1.12.2.jar                                          | None                                     |

	Loaded coremods (and transformers): 
FMLPlugin (albedo-0.1.3.jar)
  elucent.albedo.asm.ASMTransformer
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.27' Renderer: 'NVIDIA GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by Derailedzack** [comment]
I need to see if this occurs in the orginal repo.
