### ISSUE TITLE
Traveling In Nether Portals While Possessing a Mob On Servers Issues

### ISSUE THREAD

**Issue by IndieanaJones** [Ladysnake/Dissolution-Legacy#7]
[02:01:19] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_172]
        at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityPigZombie.func_70071_h_(EntityPossessableImpl.java:143) ~[?:?]
        at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[02:01:19] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\ServerFiles\New Modpack Server\.\crash-reports\crash-2020-04-12_02.01.19-server.txt

Happens pretty consistently too, usually if you enter a portal and then do so again.  The only two mods I can think of which might be causing this issue, if not dissolution itself, are NetherPortalFix and Better Nether.

**Comment by IndieanaJones** [comment]
After some further testing, it turns out NetherPortalFix causes the crashes, without it dimension swaps occur without any crashes.  However, going back and forth will eventually put you in a state where you can no longer see your body and no longer move.  Relogging fixes the issue.
