### ISSUE TITLE
New version did not fix multiple mob naming issue

### ISSUE THREAD

**Issue by Jackiecrazy** [Ladysnake/Dissolution-Legacy#9]
specifically, tragicmc3 and aoa3 both add a lost soul entity. I blacklisted one of them in the config, but game still crashes with the all-too-familiar duplicate class definition error.

**Comment by Pyrofab** [comment]
Can you post the relevant log line ?

**Comment by Jackiecrazy** [comment]
https://pastebin.com/pzBzLywB
The relevant bit, I believe, is
java.lang.LinkageError: loader (instance of  ladysnake/dissolution/common/entity/PossessableEntityFactory$ASMClassLoader): attempted  duplicate class definition for name: "ladysnake/dissolution/common/entity/EntityPossessableImpl_EntityLostSoul"
at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
    at ladysnake.dissolution.common.entity.PossessableEntityFactory$ASMClassLoader.define(PossessableEntityFactory.java:123)
    at ladysnake.dissolution.common.entity.PossessableEntityFactory.lambda$defineGenericPossessable$0(PossessableEntityFactory.java:46)
    at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
    at ladysnake.dissolution.common.entity.PossessableEntityFactory.defineGenericPossessable(PossessableEntityFactory.java:37)
    at ladysnake.dissolution.common.init.ModEntities.registerPossessables(ModEntities.java:85)

**Comment by Pyrofab** [comment]
This version does not seem to have my fix for some reason. Is it really the last one ?

**Comment by Jackiecrazy** [comment]
It is, downloaded straight off curseforge.

**Comment by sschr15** [comment]
Looking into this project now...

**Comment by sschr15** [comment]
fixed in the latest version (released as 0.3.13r2)
